### ISSUE TITLE
Installing from latest release fails

### ISSUE THREAD

**Issue by johnstantongeddes** [sbotond/rlsim#1]
I tried to install from the latest release using 

   wget https://github.com/sbotond/rlsim/tree/master/releases/rlsim-latest_amd64.tar.gz

followed by `tar -xzf rlsim-latest_amd64.tar.gz` but this gave an error message that the file was not in gzip format. 

I was able to 'Build from source' without trouble after installing golang, so not a major problem but thought I'd let you.

**Comment by sbotond** [comment]
Thanks for reporting this issue. There was a `?raw=true` missing from the download link.
It's fixed now.
