### ISSUE TITLE
A question on PCR

### ISSUE THREAD

**Issue by yfu** [sbotond/rlsim#3]
Is there any way to recover the original molecule that produces the final PCR fragments? I would like to simulate an RNA-seq dataset and know which fragments come from the same molecule (and thus are PCR duplicates).

If I open the fas file produced by `rlsim`, I see that for all fragments belonging to the same gene, they are numbers from `Fg_1` all the way to `Fg_n`, but there does not seem to be a way to figure out which are PCR duplicates.

Thanks!

**Comment by NickGoldman** [comment]
The original developer, Botond Sipos, has moved to another position and does not currently have time to work on rlsim.  We can see why you might like that feature, but I'm afraid it will not be implemented for the foreseeable future.  Nick Goldman

**Comment by yfu** [comment]
Thanks for the reply! I guess I will try other simulation tools.
